# Ignore specific files
ignore:
  - "tests/**/*"
  - "libs/**/*"
  - "src/dungeon_generation.cpp"
  - "src/dungeon_generation.h"
  - "src/dungeon_generation/ui/*"
  - "src/dungeon_generation/ui/**/*"
