# Ignore specific files

coverage:
  status:
    project:
      default: off
    patch:
      default: off
    changes:
      default: off


ignore:
  - "tests/**/*"
  - "libs/**/*"
  - "src/dungeon_generation.cpp"
  - "src/dungeon_generation.h"
  - "src/dungeon_generation/ui/*"
  - "src/dungeon_generation/ui/**/*"
